export const FETCH_VIDEOS_BEGIN = 'FETCH_VIDEOS_BEGIN';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE';
export const SET_LIST_VISIBILITY = 'SET_LIST_VISIBILITY';
