export const SET_VIDEO_PLAYED = 'SET_VIDEO_PLAYED';
export const SET_CURRENT_VIDEO_ID = 'SET_CURRENT_VIDEO_ID';
export const ADD_TO_HISTORY_STORAGE = 'ADD_TO_HISTORY_STORAGE';
export const DELETE_FROM_HISTORY_STORAGE = 'DELETE_FROM_HISTORY_STORAGE';
