export const SET_VIDEO_PLAYED = 'SET_VIDEO_PLAYED';
export const SET_CURRENT_VIDEO_ID = 'SET_CURRENT_VIDEO_ID';
export const UPDATE_HISTORY_STORAGE = 'UPDATE_HISTORY_STORAGE';
export const ADD_TO_HISTORY_STORAGE = 'ADD_TO_HISTORY_STORAGE';
export const HISTORY_STORAGE_KEY = 'dda-videos-history';
